language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/php-coveralls -v
